### ISSUE TITLE
OpenAPI3 output does not handle nullable values correctly

### ISSUE THREAD

**Issue by reieRMeister** [kminami/apib2swagger#58]
### Nominal

Rendering an API Blueprint document to OpenAPI3 with flag `--open-api-3` converts an input property like this:

```
    + errors (required, array, nullable)
```

into this:

```
  errors:
    type: array
    nullable: true
    items: {}
```

### Actual

Rendering an API Blueprint document to OpenAPI3 with flag `--open-api-3` converts an input property like this:

```
    + errors (required, array, nullable)
```

into this:

```
  errors:
    type:
      - array
      - 'null'
    items: {}
```

### Remarks

[According to the OpenAPI spec](https://swagger.io/specification/#data-types) »null is not supported as a type« and instead [the nullable property must be used](https://swagger.io/specification/#fixed-fields-20).
